### ISSUE TITLE
Lorem ipsum dolor sit amet, consectetur adipiscing

### ISSUE THREAD

**Issue by bormog** [Pushwoosh/pushwoosh-trigger-io#4]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis justo quam, euismod dictum orci eu, gravida laoreet libero. Suspendisse volutpat neque id sodales dapibus. Nullam sit amet eleifend odio. Aliquam tincidunt luctus ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus consequat lorem non hendrerit varius. Nulla commodo risus eu sapien eleifend pellentesque et ut ipsum. Sed viverra malesuada lobortis.

**Comment by wfhm** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis justo quam, euismod dictum orci eu, gravida laoreet libero

**Comment by bormog** [comment]
Duis justo quam, euismod dictum orci eu
